/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Cory' at '10/23/16 1:41 AM' with Gradle 2.13
 *
 * @author Cory, @date 10/23/16 1:41 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
